# Generated by Django 4.2.13 on 2024-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_categoryservices_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDoPosle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='do_posle_images')),
            ],
        ),
    ]
